### ISSUE TITLE
add attribute to oembed function to turn omit the script

### ISSUE THREAD

**Issue by eriktaubeneck** [eriktaubeneck/flask-twitter-oembedder#1]
Currently, twitter returns a reference to widget.js on every embedded tweet. We want to to be able to turn this off, using the `omit_script=true` query string, so that there is only one copy of `widget.js`, allowing for intent tracking.

**Comment by talos** [comment]
It's a bit piddling, but I would invert the order of the args as they have been added to implement this -- it seems much more natural to me that `omit_script` should be specified last, rather than first.  This is because it's more naturally specified as a kwarg, while the other other two credential arguments could be either kwargs or regular args.  However, if `omit_script` is first in the argument list, even if it is named, it is not possible to pass special credentials to the oembed function without using kwargs unless you specify `omit_script`, even if you don't care about its value.

**Comment by talos** [comment]
As an example, I had to user the rather verbose:

```
{{ oembed_tweet(task.tweet_id, access_token=twitter_access_token, token_secret=twitter_token_secret, omit_script=True) }}
```

instead of the (much more natural, to me):

```
{{ oembed_tweet(task.tweet_id, twitter_access_token, twitter_token_secret, omit_script=True) }}
```

because I don't feel this is particularly intuitive:

```
{{ oembed_tweet(task.tweet_id, True, twitter_access_token, twitter_token_secret) }}
```

I guess as a general rule, I like the idea that kwargs should be booleans.  Since in Python you can choose whether or not to specify your arg as a kwarg, I like that you should have the flexibility with the non-boolean parameters to not use kwargs.

**Comment by eriktaubeneck** [comment]
Cool, I like it. I'll make the change.

**Comment by eriktaubeneck** [comment]
Done.
